# Generated by Django 4.1.2 on 2022-11-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
                ('roll_no', models.CharField(max_length=10)),
                ('contact_no', models.IntegerField()),
            ],
        ),
    ]
