# Generated by Django 4.1.2 on 2022-11-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danny', '0003_alter_registration_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='text_field',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='url_field',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
