# Generated by Django 4.1.2 on 2022-11-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danny', '0005_remove_registration_text_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='url_field',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
